sudo: required

services:
 - docker

before_install:
 - docker build -t ayanworkstech/Ayanworks-docker -f Dockerfile.dev .

script:
 - docker run ayanworkstech/Ayanworks-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "MyWebApp"
  env: "Mywebapp-env"
  bucket_name: "elasticbeanstalk-ap-south-1-740567029548"
  bucket_path: "MyWebApp"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY