sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ayanworkstech/Ayanworks-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true ayanworkstech/Ayanworks-docker npm run test
